/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prasoon.noteapplication;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import java.sql.*;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Prasoon Anand
 * August 29, 2020
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * @throws java.sql.SQLException
     */
    
    public NewJFrame(){
        initComponents();
        updateList();
    }
    
    public void updateList(){
        DefaultListModel mod = new DefaultListModel();
        jList.setModel(mod);
        Connection myconn = null;
        Statement mystmt = null;
        ResultSet rs = null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          //  jNotes.append("Connecting....");
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/notes","root","root");
          //  jNotes.append("Connection successful");
            mystmt = myconn.createStatement();
            rs = mystmt.executeQuery("select * from notes");
            
            while(rs.next()){
                mod.addElement(rs.getString("name"));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    
    public static String showPasswordPrompt( Component parent, String title )
    {
        // create a new JPasswordField
        JPasswordField passwordField = new JPasswordField( );

        passwordField.setEchoChar( '*' );

        passwordField.setColumns( 20 );
        
        int returnVal = JOptionPane.showConfirmDialog( parent, passwordField, title, JOptionPane.OK_CANCEL_OPTION );
        
        //passwordField.requestFocusInWindow();
        
        if ( returnVal == JOptionPane.OK_OPTION ){
            return new String( passwordField.getPassword( ) );
        }
        else
        {
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullMenu = new javax.swing.JPanel();
        optionMenu = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        labelClose = new javax.swing.JLabel();
        buttonMinimize = new javax.swing.JPanel();
        labelMinimize = new javax.swing.JLabel();
        buttonMaximize = new javax.swing.JPanel();
        labelMaximize = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        panelNew = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelSave = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelDelete = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelSettings = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        notesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        notePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNotes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        fullMenu.setBackground(new java.awt.Color(251, 251, 251));
        fullMenu.setPreferredSize(new java.awt.Dimension(340, 500));
        fullMenu.setLayout(new java.awt.BorderLayout());

        optionMenu.setBackground(new java.awt.Color(46, 50, 53));
        optionMenu.setPreferredSize(new java.awt.Dimension(170, 500));
        optionMenu.setLayout(new java.awt.BorderLayout());

        closePanel.setBackground(new java.awt.Color(46, 50, 53));
        closePanel.setPreferredSize(new java.awt.Dimension(170, 26));
        closePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClose.setBackground(new java.awt.Color(46, 50, 53));
        buttonClose.setPreferredSize(new java.awt.Dimension(25, 25));

        labelClose.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 18)); // NOI18N
        labelClose.setForeground(new java.awt.Color(255, 255, 255));
        labelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClose.setText("X");
        labelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonCloseLayout = new javax.swing.GroupLayout(buttonClose);
        buttonClose.setLayout(buttonCloseLayout);
        buttonCloseLayout.setHorizontalGroup(
            buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonCloseLayout.createSequentialGroup()
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buttonCloseLayout.setVerticalGroup(
            buttonCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonCloseLayout.createSequentialGroup()
                .addComponent(labelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        closePanel.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 26, 26));

        buttonMinimize.setBackground(new java.awt.Color(46, 50, 53));
        buttonMinimize.setPreferredSize(new java.awt.Dimension(25, 25));

        labelMinimize.setFont(new java.awt.Font("Sitka Subheading", 1, 28)); // NOI18N
        labelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimize.setText(" _");
        labelMinimize.setToolTipText("");
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonMinimizeLayout = new javax.swing.GroupLayout(buttonMinimize);
        buttonMinimize.setLayout(buttonMinimizeLayout);
        buttonMinimizeLayout.setHorizontalGroup(
            buttonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(buttonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonMinimizeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buttonMinimizeLayout.setVerticalGroup(
            buttonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(buttonMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonMinimizeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        closePanel.add(buttonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 26, 26));

        buttonMaximize.setBackground(new java.awt.Color(46, 50, 53));
        buttonMaximize.setPreferredSize(new java.awt.Dimension(25, 25));

        labelMaximize.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        labelMaximize.setForeground(new java.awt.Color(255, 255, 255));
        labelMaximize.setText(" ▢");
        labelMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMaximizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonMaximizeLayout = new javax.swing.GroupLayout(buttonMaximize);
        buttonMaximize.setLayout(buttonMaximizeLayout);
        buttonMaximizeLayout.setHorizontalGroup(
            buttonMaximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonMaximizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonMaximizeLayout.setVerticalGroup(
            buttonMaximizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonMaximizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        closePanel.add(buttonMaximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 26, 26));

        optionMenu.add(closePanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBackground(new java.awt.Color(46, 50, 53));
        menuPanel.setPreferredSize(new java.awt.Dimension(170, 475));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNew.setBackground(new java.awt.Color(46, 50, 53));
        panelNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNewMouseExited(evt);
            }
        });
        panelNew.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                panelNewComponentHidden(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Projects\\NS Note\\Icons\\icons8_new_document_40px_1.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New");

        javax.swing.GroupLayout panelNewLayout = new javax.swing.GroupLayout(panelNew);
        panelNew.setLayout(panelNewLayout);
        panelNewLayout.setHorizontalGroup(
            panelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelNewLayout.setVerticalGroup(
            panelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuPanel.add(panelNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, 50));

        panelSave.setBackground(new java.awt.Color(46, 50, 53));
        panelSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSaveMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Projects\\NS Note\\Icons\\icons8_save_40px_2.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Save");

        javax.swing.GroupLayout panelSaveLayout = new javax.swing.GroupLayout(panelSave);
        panelSave.setLayout(panelSaveLayout);
        panelSaveLayout.setHorizontalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelSaveLayout.setVerticalGroup(
            panelSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuPanel.add(panelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 50));

        panelDelete.setBackground(new java.awt.Color(46, 50, 53));
        panelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDeleteMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Projects\\NS Note\\Icons\\icons8_delete_view_40px.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Delete");

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuPanel.add(panelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 50));

        panelSettings.setBackground(new java.awt.Color(46, 50, 53));
        panelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSettingsMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Projects\\NS Note\\Icons\\icons8_gear_40px.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Settings");

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuPanel.add(panelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 50));

        optionMenu.add(menuPanel, java.awt.BorderLayout.CENTER);

        fullMenu.add(optionMenu, java.awt.BorderLayout.LINE_START);

        notesPanel.setBackground(new java.awt.Color(251, 251, 251));
        notesPanel.setPreferredSize(new java.awt.Dimension(170, 500));
        notesPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBorder(null);

        jList.setBackground(new java.awt.Color(250, 250, 250));
        jList.setFont(new java.awt.Font("Candara Light", 0, 24)); // NOI18N
        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList);

        notesPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        fullMenu.add(notesPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(fullMenu, java.awt.BorderLayout.LINE_START);

        notePanel.setLayout(new java.awt.BorderLayout());

        jNotes.setColumns(20);
        jNotes.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jNotes.setRows(5);
        jNotes.setBorder(null);
        jScrollPane1.setViewportView(jNotes);

        notePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(notePanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    private void labelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelCloseMouseClicked

    private void labelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseExited
       // changeColor(buttonClose,new Color(46,50,53));
       labelClose.setForeground(Color.white);
    }//GEN-LAST:event_labelCloseMouseExited

    private void labelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseMouseEntered
        labelClose.setForeground(new Color(255, 94, 87));
    }//GEN-LAST:event_labelCloseMouseEntered

    private void labelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseExited
        labelMinimize.setForeground(Color.white);
    }//GEN-LAST:event_labelMinimizeMouseExited

    private void labelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseEntered
        labelMinimize.setForeground(new Color(255, 188, 45));
    }//GEN-LAST:event_labelMinimizeMouseEntered

    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(NewJFrame.ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    private void labelMaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMaximizeMouseExited
        labelMaximize.setForeground(Color.white);
    }//GEN-LAST:event_labelMaximizeMouseExited

    private void labelMaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMaximizeMouseEntered
        labelMaximize.setForeground(new Color(41, 201, 67));
    }//GEN-LAST:event_labelMaximizeMouseEntered

    private void labelMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMaximizeMouseClicked
        if(this.getExtendedState() != NewJFrame.MAXIMIZED_BOTH){
            this.setExtendedState(NewJFrame.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(NewJFrame.NORMAL);
        }
    }//GEN-LAST:event_labelMaximizeMouseClicked

    private void panelNewComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelNewComponentHidden
        // TODO add your haling code here:
    }//GEN-LAST:event_panelNewComponentHidden

    
    
    
    
    
    
    private void panelNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNewMouseClicked
        JFrame f;
        f=new JFrame();
        f.setUndecorated(true);
        String name=JOptionPane.showInputDialog(f,"Enter Title");
        
        JFrame f1;
        f1=new JFrame();
        f1.setUndecorated(true);
        String pass=showPasswordPrompt(f1,"Create Password");
                //JOptionPane.showInputDialog(f1,"Create Password");
        
        try{
            Connection myconn = null;
            Statement mystmt = null;
            ResultSet rs = null;
            var aes = new aesUtils();
            Class.forName("com.mysql.cj.jdbc.Driver");
           // jNotes.append("Connecting....");
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/notes","root","root");
           // jNotes.append("Connection successful");
            mystmt = myconn.createStatement();
            String m = " ";
            var map = aes.encrypt(pass,m);
            String message = map.get("message");
            String iv = map.get("iv");
            String salt = map.get("salt");
            
            
            String newNote = "insert into notes values('"+name+"','"+salt+"','"+iv+"','"+message+"')";
            mystmt.execute(newNote);
            updateList();
            jNotes.setText("");
            JFrame f2;   
            f2=new JFrame();
            f2.setUndecorated(true);
            JOptionPane.showMessageDialog(f2,"Created!"); 
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_panelNewMouseClicked

    private void panelNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNewMouseEntered
        changeColor(panelNew,new Color(65, 71, 71));
    }//GEN-LAST:event_panelNewMouseEntered

    private void panelNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNewMouseExited
        changeColor(panelNew,new Color(46, 50, 53));
    }//GEN-LAST:event_panelNewMouseExited

    
    
    
    private void panelSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaveMouseClicked

        try{
            var aes = new aesUtils();
            String name = jList.getSelectedValue();
            String m = jNotes.getText();
            Connection myconn = null;
            Statement mystmt = null;
            ResultSet rs = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
           // jNotes.append("Connecting....");
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/notes","root","root");
           // jNotes.append("Connection successful");
            mystmt = myconn.createStatement();

            JFrame f1;
            f1=new JFrame();
            f1.setUndecorated(true);
            String inpPass= showPasswordPrompt(f1,"Enter Password");
                    //JOptionPane.showInputDialog(f1,"Enter Password");
            
            var map = aes.encrypt(inpPass,m);
            String message = map.get("message");
            String iv = map.get("iv");
            String salt = map.get("salt");
            String save = "update notes set salt ='"+salt+"',iv ='"+iv+"', message ='"+message+"' where name ='"+name+"'";
            boolean execute = mystmt.execute(save);
            JFrame f;   
            f=new JFrame();
            f.setUndecorated(true);
            JOptionPane.showMessageDialog(f,"Saved!");  
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_panelSaveMouseClicked

    private void panelSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaveMouseEntered
        changeColor(panelSave,new Color(65, 71, 71));
    }//GEN-LAST:event_panelSaveMouseEntered

    private void panelSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaveMouseExited
        changeColor(panelSave,new Color(46, 50, 53));
    }//GEN-LAST:event_panelSaveMouseExited

    
    
    
    private void panelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseClicked
        // TODO add your handling code here:
        try{
            String name = jList.getSelectedValue();
            Connection myconn = null;
            Statement mystmt = null;
            ResultSet rs = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
           // jNotes.append("Connecting....");
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/notes","root","root");
           // jNotes.append("Connection successful");
            mystmt = myconn.createStatement();
            String getPass = "delete from notes where name = '"+name+"'";
            mystmt.execute(getPass);
            updateList();
            jNotes.setText("");
            
            JFrame f;   
            f=new JFrame();
            f.setUndecorated(true);
            JOptionPane.showMessageDialog(f,"Deleted!");  
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_panelDeleteMouseClicked

    private void panelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseEntered
        changeColor(panelDelete,new Color(65, 71, 71));
    }//GEN-LAST:event_panelDeleteMouseEntered

    private void panelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeleteMouseExited
        changeColor(panelDelete,new Color(46, 50, 53));
    }//GEN-LAST:event_panelDeleteMouseExited

    
    
    
    private void panelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSettingsMouseClicked
        // TODO add your handling code here:
        jNotes.setText("AUTHOR: PRASOON ANAND\nDATE: August 29, 2020\nEMAIL: prasoonanand@hotmail.com");
    }//GEN-LAST:event_panelSettingsMouseClicked

    private void panelSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSettingsMouseEntered
        changeColor(panelSettings,new Color(65, 71, 71));
    }//GEN-LAST:event_panelSettingsMouseEntered

    private void panelSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSettingsMouseExited
        changeColor(panelSettings,new Color(46, 50, 53));
    }//GEN-LAST:event_panelSettingsMouseExited

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        String val = jList.getSelectedValue();
        Connection myconn = null;
        Statement mystmt = null;
        ResultSet rs = null;
        var aes = new aesUtils();
        JFrame f;
        f=new JFrame();
        f.setUndecorated(true);
        String inpPass=showPasswordPrompt(f,"Enter Password");
                //JOptionPane.showInputDialog(f,"Enter Password");
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          //  jNotes.append("Connecting....");
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/notes","root","root");
          //  jNotes.append("Connection successful");
            mystmt = myconn.createStatement();
            String st = "select * from notes where name ='"+val+"'";
            rs = mystmt.executeQuery(st);
            rs.next();

            String iv = rs.getString("iv");
            String message = rs.getString("message");
            String salt = rs.getString("salt");
            HashMap<String,String> map=new HashMap<String, String>();
            map.put("password", inpPass);
            map.put("salt", salt);
            map.put("iv",iv);
            map.put("message", message);
            jNotes.setText(aes.decrypt(map));            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonClose;
    private javax.swing.JPanel buttonMaximize;
    private javax.swing.JPanel buttonMinimize;
    private javax.swing.JPanel closePanel;
    private javax.swing.JPanel fullMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList;
    private javax.swing.JTextArea jNotes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelMaximize;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel notePanel;
    private javax.swing.JPanel notesPanel;
    private javax.swing.JPanel optionMenu;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelNew;
    private javax.swing.JPanel panelSave;
    private javax.swing.JPanel panelSettings;
    // End of variables declaration//GEN-END:variables
}
